version: '3.10'

services:
  schema_storage:
    hostname: schema_storage
    build:
      context: ../..
      dockerfile: docker/docker-files/schema_storage/Dockerfile.schema_storage

    environment:
      TZ: ${TIME_ZONE}
      PSQL_POOL_MIN_CONN: ${PSQL_POOL_MIN_CONN}
      PSQL_POOL_MAX_CONN: ${PSQL_POOL_MAX_CONN}
      PSQL_DB_NAME: ${PSQL_DB_NAME}
      PSQL_DB_HOST: ${PSQL_DB_HOST}
      PSQL_DB_USER: ${PSQL_DB_USER}
      PSQL_DB_PORT: ${PSQL_DB_PORT}
      PSQL_DB_PASS: ${PSQL_DB_PASS}
    ports:
      - '8005:80'

    volumes:
      - ./logs/schema_storage/api/:/usr/src/log/schema_storage_api/:rw
      - ./logs/schema_storage/app/:/usr/src/log/schema_storage_app/:rw
