version: '3.10'

services:
  schema_storage:
    hostname: schema_storage
    build:
      context: ../..
      dockerfile: docker/docker-files/schema_storage/Dockerfile.schema_storage

    environment:
      TZ: ${TIME_ZONE}
    ports:
      - '8005:80'

    volumes:
      - ./logs/schema_storage/api/:/usr/src/log/schema_storage_api/:rw
      - ./logs/schema_storage/app/:/usr/src/log/schema_storage_app/:rw
