version: '3.10'

services:
  item_storage:
    hostname: item_storage
    build:
      context: ../..
      dockerfile: docker/docker-files/item_storage/Dockerfile.item_storage

    environment:
      TZ: ${TIME_ZONE}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
    ports:
      - '8003:80'

    volumes:
      - ./logs/item_storage/api/:/usr/src/log/item_storage_api/:rw
      - ./logs/item_storage/app/:/usr/src/log/item_storage_app/:rw
