version: '3.10'

services:
  postprocessor:
    hostname: postprocessor
    build:
      context: ../..
      dockerfile: docker/docker-files/postprocessor/Dockerfile.postprocessor

    environment:
      TZ: ${TIME_ZONE}
      MONGO_DB: ${MONGO_DB}
      MONGO_URI: ${MONGO_URI}
    ports:
      - '8010:80'

    volumes:
      - ./logs/postprocessor/app/:/usr/src/log/postprocessor_app/:rw
