version: '3.10'

services:
  scheduler:
    hostname: scheduler
    build:
      context: ../..
      dockerfile: docker/docker-files/scheduler/Dockerfile.scheduler

    environment:
      TZ: ${TIME_ZONE}
    ports:
      - '8001:80'

    volumes:
      - ./logs/scheduler/api/:/usr/src/log/scheduler_api/:rw
      - ./logs/scheduler/app/:/usr/src/log/scheduler_app/:rw
